:nick: infinityq
:altnick: infinityqq
:name: Infinity Ruby Bot
:email: dev@null.rb
:proto: irc.proto
:extprefix: .
:extpath: ./extensions/
:extensions:
  - Test_2
:servers:
  :gamesurge:
    :address: localhost

